name: Run cfstfd.py

on:
  # schedule:
  #   - cron: "0 */2 * * *"  # 每2小时的第0分钟触发
  workflow_dispatch:        # 允许手动触发
    inputs:
      ddns:
        description: '是否运行 DDNS 脚本'
        required: false
        type: boolean
        default: false

jobs:
  run-autoddns:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 确保有权限推送代码

    env:
      # 设置环境变量，使用 GitHub Secrets
      CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run cfstfd script
      run: |
        python cfstfd.py

    - name: Run autoddnsfd script (条件触发)
      if: ${{ github.event.inputs.ddns == 'true' }}  # 仅当手动触发且 ddns=true 时运行
      run: |
        python ddns/autoddnsfd.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        if git diff --quiet; then
          echo "No changes to commit."
        else
          git add .
          git commit -m "cfst: Auto-update fd.txt on $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
        fi
